apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - slimserve-deployment.yaml
  - slimserve-service.yaml
  - slimserve-data-persistentvolumeclaim.yaml
  - ingressroute.yml
namespace: slimserve
images:
  - name: ghcr.io/xeome/slimserve
    newTag: 0.3.1
