---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  namespace: argocd
spec:
  destination:
    namespace: stirling-pdf-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: stirling-pdf-chart
    repoURL: https://stirling-tools.github.io/Stirling-PDF-chart
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
