namespace: longhorn-system
resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.9.1/deploy/longhorn.yaml
patches:
  - path: namespace.yaml
    #- networkpolicy.yaml
    #  - ingressroute.yaml
