resources:
  - namespace.yml
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    releaseName: argocd
    version: 8.0.17
    namespace: argocd
    valuesInline:
      configs:
        params:
          server.insecure: true
      global:
        domain: argo.savew.dev
