name: Clean K8s Manifests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        
      - name: Install kube-neat
        run: go install github.com/itaysk/kube-neat@latest
      
      - name: Clean up YAML files recursively
        run: |
          find manifests -type f -name '*.y*ml' | while read -r file; do
            echo "Cleaning $file"
            kube-neat < "$file" > "$file.tmp" && mv "$file.tmp" "$file"
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: |
            chore(ci): clean up manifests with kubectl-neat
          branch: automated/kubectl-neat-cleanup
          title: |
            chore(ci): Cleanup manifests with kubectl-neat
          body: |
            This pull request is automatically created by a GitHub Action.
            It cleans up the YAML files in the `manifests/` directory using
            [`kube-neat`](https://github.com/itaysk/kubectl-neat).
          labels: automated, cleanup
