name: Clean K8s Manifests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install kubectl-neat using wget
        run: |
          wget https://github.com/itaysk/kubectl-neat/releases/download/latest/kubectl-neat_linux_amd64.tar.gz -O kubectl-neat.tar.gz
          tar -xzf kubectl-neat.tar.gz
          chmod +x kubectl-neat
          sudo mv kubectl-neat /usr/local/bin/kubectl-neat

      - name: Clean up YAML files recursively
        run: |
          find manifests -type f -name '*.y*ml' | while read -r file; do
            echo "Cleaning $file"
            kubectl-neat < "$file" > "$file.tmp" && mv "$file.tmp" "$file"
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: |
            chore(ci): clean up manifests with kubectl-neat
          branch: automated/kubectl-neat-cleanup
          title: |
            chore(ci): Cleanup manifests with kubectl-neat
          body: |
            This pull request is automatically created by a GitHub Action.
            It cleans up the YAML files in the `manifests/` directory using
            [`kube-neat`](https://github.com/itaysk/kubectl-neat).
          labels: automated, cleanup
